database:
  host: 10.5.0.1
  port: 3306
  user: sql_user
  password: sql_pass
  database: sql_db

ports:
  scanner_socket: 3000
  client_socket: 3500

# Define the various boxstyles that should be handled by PCRT-Scan here.
states:
  1: 
    name: storage
    alias: Check-in to Storage
    is_on_site: true
    is_stored: true
    work_in_progress: true
  2: 
    name: on_bench
    alias: Moving to Bench
    is_on_site: true
    is_stored: false
    work_in_progress: true
  3: 
    name: pending_cust_response
    alias: Waiting for Customer
    is_on_site: true
    is_stored: true
    work_in_progress: true
  4: 
    name: complete
    alias: Completed
    is_on_site: true
    is_stored: true
    work_in_progress: false
    extra_alert: "Please ensure the repair report is complete, printed and given to the customer. Check all assets are returned to the user and no company USB devices are left in the device."
  5:
    name: collected
    alias: Collected
    is_on_site: false
    is_stored: false
    work_in_progress: false
  8: 
    name: data_transfer
    alias: Move to Bench (Data Transfer)
    is_on_site: true
    is_stored: false
    work_in_progress: true
  101: 
    name: awaiting_parts
    alias: Waiting for Parts
    is_on_site: true
    is_stored: true
    work_in_progress: true

storage_prefixes:
  # The wip_prefix and complete_prefix set a prefix for the slname, i.e., if a job is WIP it will go into a storage
  # bay prefixed with wip_prefix.
  # An oversized device is any device not classified as a laptop, such as a desktop or AIO.
  wip: A
  complete: B
  oversize: O

lockouts:
  database_file: lockouts.db
  engineers:
    - Steven
    - Geoff
    - Gregg